name = "image.analysis.color_histogram"
version = "1.0.0"
display_name = "Color Histogram"
description = "Display color histogram graph from input image (RGB, HSV, Lab)"
order = 10
gui = ["reactflow", "headless"]
run_when_stopped = true
resizable = true

[[ports]]
name = "image"
data_type = "image"
direction = "inout"

[[properties]]
name = "mode"
display_name = "Mode"
type = "int"
default = 0
widget = "dropdown"
options = [
    { value = 0, label = "RGB" },
    { value = 1, label = "HSV" },
    { value = 2, label = "Lab" },
]
