name = "math.operation.sub"
version = "1.0.0"
display_name = "Sub"
description = "Subtract two numbers (a - b)"
order = 20
gui = ["reactflow", "headless"]
measure_time = false
run_when_stopped = true  # STOP時も実行可能

[[ports]]
name = "a"
data_type = "float"
direction = "in"

[[ports]]
name = "b"
data_type = "float"
direction = "in"

[[ports]]
name = "a-b"
data_type = "float"
direction = "out"
