name = "image.deep_learning.low_light_image_enhancement"
version = "1.0.0"
display_name = "Low-Light Image Enhancement"
description = "Low-Light Image Enhancement using deep learning models"
order = 13
gui = ["reactflow", "headless"]
measure_time = true

[[ports]]
name = "image"
data_type = "image"
direction = "inout"

[[properties]]
name = "process_size"
display_name = "Size"
type = "int"
default = 0
widget = "dropdown"
options = [
    { value = 0, label = "Original" },
    { value = 1, label = "1280x720" },
    { value = 2, label = "640x360" },
    { value = 3, label = "320x180" },
]

[[properties]]
name = "model"
display_name = "Model"
type = "int"
default = 0
widget = "dropdown"
disabled_while_streaming = true
options = [
    { value = 0, label = "MobileIE" },
    { value = 1, label = "TBEFN" },
    { value = 2, label = "CPGA-Net" },
]

[[properties]]
name = "use_gpu"
display_name = "Use GPU"
type = "bool"
default = true
widget = "checkbox"
disabled_while_streaming = true
requires_gpu = true
