name = "image.transform.rotate"
version = "1.0.0"
display_name = "Rotate"
description = "Rotate image by specified angle"
order = 161
gui = ["reactflow", "headless"]

[[ports]]
name = "image"
data_type = "image"
direction = "inout"

[[ports]]
name = "angle"
data_type = "float"
direction = "in"

[[properties]]
name = "angle"
display_name = "Angle"
type = "int"
default = 0
min = -360
max = 360
step = 10
widget = "number_input"

[[properties]]
name = "border_color"
display_name = "Border Color"
type = "string"
default = "#808080"
widget = "color_picker"

