name = "text.deep_learning.language_classification"
version = "1.0.1"
display_name = "Language Classification"
description = "Classify the language of input text using deep learning models"
order = 10
gui = ["reactflow", "headless"]
measure_time = true

[[ports]]
name = "text_in"
display_name = "Text"
data_type = "string"
direction = "in"
preview = false

[[ports]]
name = "result_json"
data_type = "string"
direction = "out"
preview = false

[[properties]]
name = "model"
display_name = "Model"
type = "int"
default = 0
widget = "dropdown"
disabled_while_streaming = true
options = [
    { value = 0, label = "MediaPipe Language Detector" },
]
