name = "image.analysis.lbp_histogram"
version = "1.0.0"
display_name = "LBP Histogram"
description = "Display Local Binary Pattern histogram from input image"
order = 20
gui = ["reactflow", "headless"]
run_when_stopped = true
resizable = true

[[ports]]
name = "image"
data_type = "image"
direction = "inout"

[[properties]]
name = "mode"
display_name = "Mode"
type = "int"
default = 1
widget = "dropdown"
options = [
    { value = 0, label = "LBP" },
    { value = 1, label = "Uniform LBP" },
]
